services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\LogoBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaLogoBundle.php'
